import type { Vehicle } from './vehicles';

export type RustWasmModule = {
  set_vehicles: (vehiclesJson: string) => unknown;
  filter_vehicles: (query: string, categoryKey: string) => unknown;
  default?: () => Promise<unknown>;
};

export async function tryInitRustWasm(vehicles: Vehicle[]): Promise<RustWasmModule | null> {
  try {
    // wasm-pack output path will be generated by you.
    // @vite-ignore prevents Vite from trying to resolve the file at build time.
    const mod: RustWasmModule = await import(/* @vite-ignore */ '../../wasm/pkg/revcards_wasm');
    if (typeof mod.default === 'function') {
      await mod.default();
    }
    mod.set_vehicles(JSON.stringify(vehicles));
    return mod;
  } catch (e) {
    // Keep JS mode working when wasm isn't built yet.
    return null;
  }
}

export async function rustFilter(
  wasm: RustWasmModule,
  vehicles: Vehicle[],
  query: string,
  categoryKey: string
): Promise<Vehicle[]> {
  // filter_vehicles returns JsValue (array of indices)
  const jsVal: any = wasm.filter_vehicles(query, categoryKey);
  const indices: number[] = Array.isArray(jsVal) ? jsVal : (jsVal?.toJSON?.() ?? []);
  return indices.map((i) => vehicles[i]).filter(Boolean);
}

